#ifndef GAME_CLIENT_COMPONENTS_COMP_PULSE_VERSION_H
#define GAME_CLIENT_COMPONENTS_COMP_PULSE_VERSION_H

#define PULSE_BUILD_DATE __DATE__ ", " __TIME__
#define PULSE_VERSIONNR 051
#define PULSE_VERSION "0.5.1"

#endif
